version: "3.8"

services:
  traefik:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: node:14
    command: npm run dev
    env_file: ./.env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "3001:3001"
    labels:
      - "traefik.http.routers.wozo.rule=Host(`wozo.localhost`)"
      - "traefik.http.services.wozo.loadbalancer.server.port=3000"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 5432:5432
